In [1]:
import pandas as pd
import os

os.chdir("..")

In [2]:
df = pd.read_csv("collection/merged_data.csv")

In [4]:
df

,company_name,world_rank_2022,world_rank_2021,world_rank_2020,mcap_2022,mcap_2021,mcap_2020,annual_revenue,annual_net_income,total_assets,...,cashflow_investing_2021,cashflow_investing_2020,norm_eps_2019,cashflow_investing_2019,status,use_cases,slugs_matched,related_companies,total_articles,profile_tier
0,LONGFOR GROUP HOLDINGS,677,775.0,539.0,3.118800e+10,3.547500e+10,2.891200e+10,3.509200e+10,3.747000e+09,1.375600e+11,...,-6.822200e+09,-5.796000e+09,2.97,-4.933600e+09,NaN,NaN,NaN,NaN,NaN,NaN
1,BAIDU,354,346.0,255.0,5.336800e+10,7.375400e+10,5.302900e+10,1.955800e+10,1.607000e+09,5.970300e+10,...,-4.401600e+09,-3.857000e+09,NaN,NaN,True,[],"['baidu', 'baidu-ai-cloud', 'baidu-ai-accelera...","['Baidu', 'Baidu AI Cloud', 'Baidu AI Accelera...",24.0,3.0
2,GREAT WALL MOTOR COMPANY,350,224.0,1482.0,5.365500e+10,4.620400e+10,1.033600e+10,1.985000e+10,9.790000e+08,2.552600e+10,...,-1.563800e+09,-1.622600e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CHONGQING ZHIFEI BIOLOGICAL PRODUCTS,729,469.0,1346.0,2.864000e+10,3.622500e+10,1.133400e+10,4.461000e+09,1.485000e+09,4.372000e+09,...,-2.828000e+08,-1.260000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LUZHOU LAOJIAO,346,507.0,908.0,5.432400e+10,5.070700e+10,1.750800e+10,3.004000e+09,1.158000e+09,6.288000e+09,...,-3.752000e+08,-3.038000e+08,3.16,-6.370000e+08,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,SAMSARA NETWORKS,2562,2562.0,2562.0,NaN,NaN,NaN,2.500000e+08,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,COLFAX CORPORATION,2528,2557.0,2963.0,6.934000e+09,4.530000e+09,4.397000e+09,3.854000e+09,7.100000e+07,8.515000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,ONEMAIN HOLDINGS,2543,2421.0,2427.0,6.880000e+09,6.469000e+09,5.764000e+09,4.973000e+09,1.314000e+09,2.207900e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,UNITED STATES STEEL CORPORATION,2546,2542.0,5211.0,6.864000e+09,3.696000e+09,1.953000e+09,2.027500e+10,4.174000e+09,1.781600e+10,...,-8.400000e+08,-5.600000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000,PROSPERITY BANCSHARES,2491,2784.0,2118.0,7.114000e+09,6.420000e+09,6.828000e+09,1.098000e+09,5.190000e+08,3.783300e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN